sudo: required

language: go

services:
  - docker

install:
  - go get -v github.com/gohugoio/hugo

script:
  - hugo
  - docker build -t j0weiss/devblog .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push j0weiss/devblog