baseURL = "http://localhost:80/"
languageCode = "en-us"
title = "The simple devBlog!"
theme = "minimal"

[params]
    author = "Johannes Weiß"
    description = ""
    githubUsername = "j0weiss"
    accent = "steelblue"
    showBorder = false
    backgroundColor = "white"
    font = "Quicksand" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "github"
    highlightLanguages = ["shell"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "envelope-o"
#     weight = 1

[[menu.icon]]
    url = "https://github.com/j0weiss/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/j0weiss/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://stackoverflow.com/users/4238964/j0weiss"
    name = "stack-overflow"
    weight = 5
